### PR TITLE
fix: NFTs not loading

### LINKED ISSUE #1102: NFTs aren't loading in MyMeta
### What happened?

The requests to OpenSea to load a user's NFTs are being rejected with a HTTP 403 forbidden.

I don't know if it is an issue of the access token being canceled, or it could be something deeper.

One potential issue is the environment variable used to provide the token is [`NEXT_OPENSEA_API_KEY`](//github.com/MetaFam/TheGame/blob/f5295c324244f2973ea419c588e784c142a8091b/packages/web/config.ts#L16). According to [the documentation](//nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser), variables being accessed by the browser need to be prefaced with `NEXT_PUBLIC_`.

### What did you expect to happen?

On a user's MyMeta profile page, the "NFT Gallery" should have content in it.

### How can we reproduce the problem (as minimally as possible)?

Visit [test.metagame.wtf/me](//test.metagame.wtf/me) and view the NFT Gallery.

### Is there anything else we need to know?

You can see the error for the rejected connection to OpenSea in the browser console.

### PR DESCRIPTION
**Pull request by dan13ram**
## Overview

**What features/fixes does this PR include?**
Fixes NFTs not displaying on the user's profile

**Please provide the GitHub issue number**

Closes #1102

## Follow up Improvement Ideas

- [ ] move away from opensea if possible
- [ ] look at caching nfts in hasura as described in #1133 

## Implementation
Moved opensea api key usage into server side to safe-guard the api key. 

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

File: packages/web/utils/openseaHelpers.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    const {
+      address,
+      symbol: tokenSymbol,
+      decimals,
+      usdPrice,
+    } = event.paymentToken;
+
+    const symbol = ETH_ADDRESSES.includes(address) ? 'Ξ' : tokenSymbol;
+    const price = Number(utils.formatUnits(event.totalPrice, decimals));
+    const priceInUSD = usdPrice ? price * Number(usdPrice) : 0;
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:49]: If `usdPrice` is falsey, `priceInUSD` is acting as a boolean rather than a number.

```suggestion
    const priceInUSD = usdPrice ? price * Number(usdPrice) : false;
```

File: packages/web/utils/openseaHelpers.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+      (collectible: Collectible) =>
+        !!collectible.title && !!collectible.imageUrl,
+    );
+
+const ETH_ADDRESSES = [
+  '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // wETH
+  '0x0000000000000000000000000000000000000000', // ETH
+];
+
+const getPriceString = (event: AssetEvent | null): string => {
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:38]:
```suggestion
const getPriceString = (event: Maybe<AssetEvent>): string => {
```

File: packages/web/utils/openseaHelpers.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
+import { utils } from 'ethers';
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:1]: Arguable, but I think using the name better contextualizes the methods getting called on it.

```suggestion
import { utils as ethers } from 'ethers';
```

File: packages/web/utils/openseaHelpers.ts [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+  if (event?.paymentToken) {
+    const {
+      address,
+      symbol: tokenSymbol,
+      decimals,
+      usdPrice,
+    } = event.paymentToken;
+
+    const symbol = ETH_ADDRESSES.includes(address) ? 'Ξ' : tokenSymbol;
+    const price = Number(utils.formatUnits(event.totalPrice, decimals));
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:48]:
```suggestion
    const price = Number(ethers.formatUnits(event.totalPrice, decimals));
```

File: packages/web/utils/openseaHelpers.ts [hunk 5]
```diff
@@ -0,0 +1,55 @@
+import { utils } from 'ethers';
+import { AssetEvent, OpenSeaAsset } from 'opensea-js/lib/types';
+
+export type Collectible = {
+  address: string;
+  tokenId: string;
+  title: string;
+  imageUrl: string;
+  openseaLink: string;
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:9]:
```suggestion
  openSeaLink: string;
```

File: packages/web/utils/openseaHelpers.ts [hunk 6]
```diff
@@ -0,0 +1,55 @@
+import { utils } from 'ethers';
+import { AssetEvent, OpenSeaAsset } from 'opensea-js/lib/types';
+
+export type Collectible = {
+  address: string;
+  tokenId: string;
+  title: string;
+  imageUrl: string;
```
Comment (dysbulic) [inline packages/web/utils/openseaHelpers.ts:8]:
```suggestion
  imageURL: string;
```

File: packages/web/config.ts [hunk 7]
```diff
@@ -34,4 +33,5 @@ export const CONFIG = {
   calendarId: 'nih59ktgafmm64ed4qk6ue8vv4@group.calendar.google.com',
   googleDataApiKey: process.env.NEXT_PUBLIC_YOUTUBE_API_KEY,
   web3StorageToken: process.env.WEB3_STORAGE_TOKEN || '',
+  openseaApiKey: process.env.OPENSEA_API_KEY || '',
```
Comment (dysbulic) [inline packages/web/config.ts:36]:
```suggestion
  openSeaApiKey: process.env.OPENSEA_API_KEY || '',
```

File: packages/web/pages/api/opensea.ts [hunk 8]
```diff
@@ -0,0 +1,39 @@
+import { CONFIG } from 'config';
+import { utils } from 'ethers';
+import { NextApiRequest, NextApiResponse } from 'next';
+import { OpenSeaAPI } from 'opensea-js';
+import { OpenSeaAssetQuery } from 'opensea-js/lib/types';
+import { Collectible, parseOpenSeaAssets } from 'utils/openseaHelpers';
+
+const opensea = new OpenSeaAPI({ apiKey: CONFIG.openseaApiKey });
```
Comment (dysbulic) [inline packages/web/pages/api/opensea.ts:8]:
```suggestion
const opensea = new OpenSeaAPI({ apiKey: CONFIG.openSeaApiKey });
```

**Review by dysbulic — APPROVED** [review]
I didn't realize we were proxying these requests. I suppose though that since @alalonde pointed out the key isn't in the request headers that's really the only possibility.

I had a couple capitalization and variable use questions, but it looks solid to me.

------

I just tried the [test instance](//frontend-pr-1147-mjhnbmqqna-uk.a.run.app), and I'm getting back an error "`Access denied | api.opensea.io used Cloudflare to restrict access`". Does this work for you?

**Comment by dan13ram** [comment]
@dysbulic Probably need to fix/add the env var for the api key on the google deployment? 

https://the-game-git-fix-nfts-metafam.vercel.app/player/peth-yursick this is working for me on vercel.

File: .github/workflows/gcp-deploy.yaml [hunk 9]
```diff
@@ -486,9 +486,10 @@ jobs:
             --ingress all \
             --max-instances 1 \
             --allow-unauthenticated \
-            --set-env-vars NEXT_PUBLIC_GRAPHQL_URL=${{needs.env.outputs.GRAPHQL_URL}} \
             --set-env-vars WEB3_STORAGE_TOKEN=${{secrets.WEB3_STORAGE_TOKEN}} \
+            --set-env-vars OPENSEA_API_KEY=${{secrets.OPENSEA_API_KEY}} \
             --set-env-vars NEXT_PUBLIC_IMGIX_TOKEN=${{secrets.IMGIX_TOKEN}}
```
Comment (alalonde) [inline .github/workflows/gcp-deploy.yaml:491]: I believe you need a trailing \ here

**Review by alalonde — COMMENTED** [review]
Thanks for putting the API key in the next.js API, much better. 

Once that trailing slash is added, should be gtg.
