### PR TITLE
fix: dao memberships without title are also displayed

### LINKED ISSUE #863: Non-mainnet DAO memberships don't render properly on the setup / memberships page
image

### PR DESCRIPTION
**Pull request by Udit-takkar**
## Overview

Closes #863 

## Implementation

Made all DAO membership display properly on the `/profile/setup`.
Also added Image and Url link of the dao

Note: this change won't be visible on the deployed website. you would first have to allow this page to show.
For that you would have to go to `web/lib/hooks/index`  and comment some things

## Assets

Screenshot 2021-11-20 at 5 36 20 PM

### CODE REVIEW

File: packages/web/components/Setup/SetupMemberships.tsx [hunk 1]
```diff
@@ -78,3 +81,43 @@ export const SetupMemberships: React.FC<SetupMembershipsProps> = ({
     </FlexContainer>
   );
 };
+
+type MembershipListingProps = {
+  member: Membership;
+};
+
+const MembershipListing: React.FC<MembershipListingProps> = ({ member }) => {
```
Comment (alalonde) [inline packages/web/components/Setup/SetupMemberships.tsx:89]: Let's pull this shared component up into its own file, along with the `getDaoLink`, `getImageMoloch` etc functions, so that both  `SetupMemberships` and `PlayerMemberships` can use it

**Review by alalonde — CHANGES_REQUESTED** [review]

File: packages/web/components/Setup/SetupMemberships.tsx (hunk 1 above)
Comment (Udit-takkar) [reply packages/web/components/Setup/SetupMemberships.tsx:89]: okay makes sense

**Comment by Udit-takkar** [comment]
Made the changes and rebased
LGTM

**Review by alalonde — APPROVED** [review]
Thanks, looks good!
