### PR TITLE
fixed collectible favorites schema bug

### LINKED ISSUE #655: [MyMeta] Fix collectibleFavorites logic in backend remote schema
This is failing for username `dekan` with ethereumAddress `0xced608aa29bb92185d9b6340adcbfa263dae075b`

Query to reproduce bug
```
  query Test {
    player(where: { username: { _eq: "dekan" } }) {
      id
      username
      box_profile {
        description
        emoji
        ethereumAddress
        coverImageUrl
        imageUrl
        job
        location
        name
        collectiblesFavorites {
          tokenId
          address
        }
      }
    }
  }
```

But the following doesn't throw up any error: 
```
  query Test {
    player(where: { username: { _eq: "dekan" } }) {
      id
      username
      box_profile {
        description
        emoji
        ethereumAddress
        coverImageUrl
        imageUrl
        job
        location
        name
      }
    }
  }
```

### PR DESCRIPTION
**Pull request by dan13ram**
Closes #655

### CODE REVIEW

File: packages/backend/src/handlers/remote-schemas/resolvers/getBoxProfile/resolver.ts [hunk 1]
```diff
@@ -51,12 +51,22 @@ function getImage(
...
+
 function getCollectiblesFavourites(
   collectiblesFavorites: Array<CollectiblesFavorite> | null | undefined,
 ) {
   if (!collectiblesFavorites) return [];
-  return collectiblesFavorites.map(({ address, token_id }) => ({
-    address,
-    tokenId: token_id,
-  }));
+  console.log(collectiblesFavorites);
```
Comment (alalonde) [inline packages/backend/src/handlers/remote-schemas/resolvers/getBoxProfile/resolver.ts:62]: Do you intend to use this to debug further?

**Review by alalonde — APPROVED** [review]

File: packages/backend/src/handlers/remote-schemas/resolvers/getBoxProfile/resolver.ts (hunk 1 above)
Comment (dan13ram) [reply packages/backend/src/handlers/remote-schemas/resolvers/getBoxProfile/resolver.ts:62]: Nope! That was a mistake.
