### PR TITLE
Fixed username updating

### LINKED ISSUE #364: [MyMeta] Can't update username

### PR DESCRIPTION
**Pull request by alalonde**
Resolves #364. Also confirmed that you can't update somebody else's username (at least using that graphql mutation)

### CODE REVIEW

File: packages/web/graphql/mutations/updateUsername.ts [hunk 1]
```diff
@@ -1,12 +1,10 @@
 import gql from 'fake-tag';
 
 export const UpdateUsernameMutation = gql`
-  mutation UpdatePlayerUsername($username: String!) {
-    update_player(_set: { username: $username }, where: {}) {
-      returning {
-        id
-        username
-      }
+  mutation UpdatePlayerUsername($playerId: uuid!, $username: String!) {
```
Comment (dan13ram) [inline packages/web/graphql/mutations/updateUsername.ts:4]: what error was the previous mutation causing ?

The backend is setup that only the player can update the player data information, which is checked from the header `X-Hasura-User-Id`

In case the backend is insecure => that is, if one player is able to update another players' data, then we need to update the permissions on the backend.

**Review by dan13ram — APPROVED** [review]
LGTM. Perhaps this needs to be solved on the backend though

File: packages/web/graphql/mutations/updateUsername.ts (hunk 1 above)
Comment (alalonde) [reply packages/web/graphql/mutations/updateUsername.ts:4]: It didn't work at all and just failed silently. I suspect it's because there is that hasura permission you mentioned. I tried to update another player's username in my testing and its not possible.
